 steps:
  - name: 'gcr.io/cloud-builders/mvn' 
    args: ['clean', 'package', 'com.google.cloud.tools:jib-maven-plugin:3.4.0:build', '-Dimage=us-central1-docker.pkg.dev/resonant-triode-408814/spring-petclinic', '-DskipTests']
