  steps: 
  # Build the container image  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/resonant-triode-408814/spring-petclinic:tag1', '.']
  images:
  - 'us-central1-docker.pkg.dev/resonant-triode-408814/spring-petclinic:tag1'
