  steps:
  # Build the container image  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/resonant-triode-408814/spring-petclinic:tag1', '.']
  images:
  - 'gcr.io/resonant-triode-408814/spring-petclinic:tag1'
